name: Makefile Check

on: [push]

jobs:
  norm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install preprerequisites
      run: mkdir installs/; mkdir installs/criterion/;
            cd installs/criterion;
            sudo ./.github/workflows/install_criterion.sh;
            cd ..; mkdir buildcsfml/; cd buildcsfml;
            sudo ./.github/workflows/build_csfml.sh

    - name: make
      run: make

    - name: make re
      run: make re

    - name: make fclean
      run: make fclean

    - name: make all
      run: make all

    - name: make clean
      run: make clean
